/* Generated by startup_generator */
// Copyright (c) MakerLab.me & Andy Sze(andy.sze.mail@gmail.com).

#include <stm32f4xx.h>
#include <core_cm4.h>

extern void _estack(void);  // to force type checking
void Reset_Handler(void);
void default_handler (void) 
{
  while(1);
}

// Arduino: we must setup hardware before doing this
//void __attribute__ ((weak)) __libc_init_array (void){}

// Linker supplied pointers

extern unsigned long _sidata;
extern unsigned long _sdata;
extern unsigned long _edata;
extern unsigned long _sbss;
extern unsigned long _ebss;

extern int main(void);

void Reset_Handler(void) {

   unsigned long *src, *dst;

   src = &_sidata;
   dst = &_sdata;

   // Copy data initializers

    while (dst < &_edata)
      *(dst++) = *(src++);

   // Zero bss

   dst = &_sbss;
   while (dst < &_ebss)
       *(dst++) = 0;

  //SystemInit();
  //__libc_init_array();
  main();
  while(1) {}
}




__attribute__ ((section(".isr_vector")))

const DeviceVectors exception_table = {

	_estack,
	Reset_Handler,
	NMI_Handler,
	HardFault_Handler,
	MemManage_Handler,
	BusFault_Handler,
	UsageFault_Handler,
	0, 0, 0, 0,
	SVC_Handler,
	DebugMon_Handler,
	0,
	PendSV_Handler,
	SysTick_Handler,


	WWDG_IRQHandler,
	PVD_IRQHandler,
  TAMP_STAMP_IRQHandler,             /* Tamper and TimeStamps through the EXTI line */            
	RTC_WKUP_IRQHandler,               /* RTC Wakeup through the EXTI line */                      
  FLASH_IRQHandler,
	RCC_IRQHandler,
	EXTI0_IRQHandler,
	EXTI1_IRQHandler,
	EXTI2_IRQHandler,
	EXTI3_IRQHandler,
	EXTI4_IRQHandler,
  DMA1_Stream0_IRQHandler,           /* DMA1 Stream 0                */                  
  DMA1_Stream1_IRQHandler,           /* DMA1 Stream 1                */                   
  DMA1_Stream2_IRQHandler,           /* DMA1 Stream 2                */                   
  DMA1_Stream3_IRQHandler,           /* DMA1 Stream 3                */                   
  DMA1_Stream4_IRQHandler,           /* DMA1 Stream 4                */                   
  DMA1_Stream5_IRQHandler,           /* DMA1 Stream 5                */                   
  DMA1_Stream6_IRQHandler,           /* DMA1 Stream 6                */                   

	ADC_IRQHandler,
  CAN1_TX_IRQHandler,                /* CAN1 TX                      */                         
  CAN1_RX0_IRQHandler,               /* CAN1 RX0                     */                          
  CAN1_RX1_IRQHandler      ,
  CAN1_SCE_IRQHandler      ,
	EXTI9_5_IRQHandler,
  TIM1_BRK_TIM9_IRQHandler,          /* TIM1 Break and TIM9          */         
  TIM1_UP_TIM10_IRQHandler,          /* TIM1 Update and TIM10        */         
  TIM1_TRG_COM_TIM11_IRQHandler,     /* TIM1 Trigger and Commutation and TIM11 */
	TIM1_CC_IRQHandler,
	TIM2_IRQHandler,
	TIM3_IRQHandler,
	TIM4_IRQHandler,

	I2C1_EV_IRQHandler,
	I2C1_ER_IRQHandler,
	I2C2_EV_IRQHandler,
	I2C2_ER_IRQHandler,
	SPI1_IRQHandler,
	SPI2_IRQHandler,
	USART1_IRQHandler,
	USART2_IRQHandler,
	USART3_IRQHandler,
	EXTI15_10_IRQHandler,
	RTC_Alarm_IRQHandler,
  OTG_FS_WKUP_IRQHandler,

  TIM8_BRK_TIM12_IRQHandler,
  TIM8_UP_TIM13_IRQHandler  ,
  TIM8_TRG_COM_TIM14_IRQHandler,
  TIM8_CC_IRQHandler  ,
	DMA1_Stream7_IRQHandler,
	FSMC_IRQHandler,
	SDIO_IRQHandler,
	TIM5_IRQHandler,
	SPI3_IRQHandler,
	UART4_IRQHandler,
	UART5_IRQHandler,
	TIM6_DAC_IRQHandler,
	TIM7_IRQHandler,

  DMA2_Stream0_IRQHandler  ,         /* DMA2 Stream 0                */                   
  DMA2_Stream1_IRQHandler  ,         /* DMA2 Stream 1                */                   
  DMA2_Stream2_IRQHandler  ,         /* DMA2 Stream 2                */                   
  DMA2_Stream3_IRQHandler  ,         /* DMA2 Stream 3                */                   
  DMA2_Stream4_IRQHandler  ,         /* DMA2 Stream 4                */                   
  ETH_IRQHandler           ,         /* Ethernet                     */                   
  ETH_WKUP_IRQHandler      ,         /* Ethernet Wakeup through EXTI line */                     
  CAN2_TX_IRQHandler       ,         /* CAN2 TX                      */                          
  CAN2_RX0_IRQHandler      ,         /* CAN2 RX0                     */                          
  CAN2_RX1_IRQHandler      ,         /* CAN2 RX1                     */                          
  CAN2_SCE_IRQHandler      ,         /* CAN2 SCE                     */                          
  OTG_FS_IRQHandler        ,         /* USB OTG FS                   */                   
  DMA2_Stream5_IRQHandler  ,         /* DMA2 Stream 5                */                   
  DMA2_Stream6_IRQHandler  ,         /* DMA2 Stream 6                */                   
  DMA2_Stream7_IRQHandler  ,         /* DMA2 Stream 7                */                   
  USART6_IRQHandler        ,         /* USART6                       */                    
  I2C3_EV_IRQHandler       ,         /* I2C3 event                   */                          
  I2C3_ER_IRQHandler       ,         /* I2C3 error                   */                          
  OTG_HS_EP1_OUT_IRQHandler,         /* USB OTG HS End Point 1 Out   */                   
  OTG_HS_EP1_IN_IRQHandler ,         /* USB OTG HS End Point 1 In    */                   
  OTG_HS_WKUP_IRQHandler   ,         /* USB OTG HS Wakeup through EXTI */                         
  OTG_HS_IRQHandler        ,         /* USB OTG HS                   */                   
  DCMI_IRQHandler          ,         /* DCMI                         */                   
  CRYP_IRQHandler          ,         /* CRYP crypto                  */                   
  HASH_RNG_IRQHandler      ,         /* Hash and Rng                 */
  FPU_IRQHandler           ,         /* FPU                          */                         

	};


